baseURL = "http://lekan.wtf/"
languageCode = "en-us"
title = "Lekan Adigun"
theme = "hyde"
[params]
  themeColor = ""
  description = "Welcome to my blog! I will be writing about Golang, backend engineering, cloud native and sometimes, what I am currently working on."
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/adigunhammedolalekan/"},
      {Name = "Twitter", URL = "https://twitter.com/L3kanAdigun/"}
  ]
