baseURL = "https://lekan.wtf/"
languageCode = "en-us"
title = "Lekan Adigun"
theme = "hyde"
[params]
  themeColor = ""
  description = "Welcome to my website! Where i write about Golang, Backend engineering, DevOps and sometimes, what I am currently working on."
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/adigunhammedolalekan/"},
      {Name = "Twitter", URL = "https://twitter.com/L3kanAdigun/"}
  ]
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "manni"
    tabWidth = 4
